-- --------------------------------------------------------
-- Хост:                         127.0.0.1
-- Версия сервера:               5.5.50 - MySQL Community Server (GPL)
-- ОС Сервера:                   Win32
-- HeidiSQL Версия:              9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Дамп структуры базы данных NewsPortal
CREATE DATABASE IF NOT EXISTS `newsportal` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `NewsPortal`;


-- Дамп структуры для таблица NewsPortal.Category
CREATE TABLE IF NOT EXISTS `Category` (
  `Ct_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Ct_Name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`Ct_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

-- Дамп данных таблицы NewsPortal.Category: ~8 rows (приблизительно)
/*!40000 ALTER TABLE `Category` DISABLE KEYS */;
INSERT INTO `Category` (`Ct_Id`, `Ct_Name`) VALUES
	(1, 'Main'),
	(2, 'Country'),
	(3, 'Economic'),
	(4, 'Politic'),
	(5, 'Social'),
	(6, 'Sport'),
	(7, 'Weather'),
	(8, 'Other');
/*!40000 ALTER TABLE `Category` ENABLE KEYS */;


-- Дамп структуры для таблица NewsPortal.News
CREATE TABLE IF NOT EXISTS `News` (
  `Ns_Id` int(11) NOT NULL AUTO_INCREMENT,
  `Ns_Name` varchar(50) NOT NULL DEFAULT '0',
  `Ns_Cat` int(11) NOT NULL,
  `Ns_Header` varchar(50) NOT NULL DEFAULT '0',
  `Ns_Text` text NOT NULL,
  `Ns_Img` varchar(50) NOT NULL DEFAULT '0',
  `Ns_Data` date DEFAULT NULL,
  `Ns_Autor` varchar(50) DEFAULT NULL,
  KEY `Ns_Id_Key` (`Ns_Id`),
  KEY `FK_New_Category` (`Ns_Cat`),
  CONSTRAINT `FK_New_Category` FOREIGN KEY (`Ns_Cat`) REFERENCES `Category` (`Ct_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;

-- Дамп данных таблицы NewsPortal.News: ~29 rows (приблизительно)
/*!40000 ALTER TABLE `News` DISABLE KEYS */;
INSERT INTO `News` (`Ns_Id`, `Ns_Name`, `Ns_Cat`, `Ns_Header`, `Ns_Text`, `Ns_Img`, `Ns_Data`, `Ns_Autor`) VALUES
	(2, 'Test', 1, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (2)', '2017-01-06', 'Apsent'),
	(4, 'Test', 1, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (4)', '2017-01-04', 'Apsent'),
	(1, 'Test', 1, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (1)', '2017-01-07', 'Apsent'),
	(3, 'Test', 1, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (3)', '2017-01-05', 'Apsent'),
	(7, 'Test', 3, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (7)', '2017-01-05', 'Apsent'),
	(6, 'Test', 3, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (6)', '2017-01-07', 'Apsent'),
	(5, 'Test', 3, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (5)', '2017-01-05', 'Apsent'),
	(9, 'Test', 3, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (8)', '2017-01-03', 'Apsent'),
	(10, 'Test', 2, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (9)', '2017-01-01', 'Apsent'),
	(11, 'Test', 2, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (10)', '2017-01-02', 'Apsent'),
	(12, 'Test', 2, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (11)', '2016-12-31', 'Apsent'),
	(13, 'Test', 2, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (12)', '2016-12-30', 'Apsent'),
	(14, 'Test', 4, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (13)', '2016-12-29', 'Apsent'),
	(15, 'Test', 4, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (14)', '2016-12-27', 'Apsent'),
	(16, 'Test', 4, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (15)', '2016-12-26', 'Apsent'),
	(17, 'Test', 4, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (16)', '2016-12-25', 'Apsent'),
	(18, 'Test', 5, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (17)', '2017-01-10', 'Apsent'),
	(19, 'Test', 5, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (18)', '2017-01-05', 'Apsent'),
	(20, 'Test', 5, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (19)', '2016-12-20', 'Apsent'),
	(21, 'Test', 5, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (20)', '2016-12-19', 'Apsent'),
	(22, 'Test', 6, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (21)', '2016-12-26', 'Apsent'),
	(23, 'Test', 6, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (22)', '2016-12-24', 'Apsent'),
	(24, 'Test', 6, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (23)', '2016-12-30', 'Apsent'),
	(25, 'Test', 6, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (24)', '2017-01-06', 'Apsent'),
	(26, 'Test', 7, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (25)', '2016-12-31', 'Apsent'),
	(27, 'Test', 7, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (26)', '2017-01-07', 'Apsent'),
	(28, 'Test', 7, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (27)', '2016-12-22', 'Apsent'),
	(29, 'Test', 7, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (28)', '2016-12-30', 'Apsent'),
	(30, 'Test', 8, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (29)', '2017-01-07', 'Apsent'),
	(31, 'Test', 8, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (30)', '2016-12-31', 'Apsent'),
	(32, 'Test', 8, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (31)', '2016-12-29', 'Apsent'),
	(33, 'Test', 8, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (32)', '2016-12-31', 'Apsent'),
	(34, 'Test', 8, 'this is news header', 'sdbfkhsbfbsdfb hbsdbfb  sdnkdsjksdnfkjnfkjnl\r\ns;dmflksdnflksnflkns\r\ns nlsnfglnslkgnslgnlsnglsnglksnglsnglsnglksnglnslnglskngslngwngslknsglknglksnglksnlkgnslkngs\r\ns;kgnlksnglksfnglslgnslgnsljhgljsnga/lng\'wen4lkws\r\nskgneourgljsngljsfgoushgohljsnglsngljsh82enwlfmsvjpirjv;kr\r\nslkgnosghoushgushguoshgiushgkjgnwljnosuhgoushglwse;2ksfclksnvfbgjgrwe\r\nsdljihfiekkfpoterhwneks[dpfs[pdf\'sd;f\';s,df/\'sd,fs;ljdfijsdoifslkdm\r\nsd;lfms;f;sjd;fsjs;kfjpsjdffs;kj', 'images (33)', '2016-12-31', 'Apsent');
/*!40000 ALTER TABLE `News` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
